### ISSUE TITLE
Writing/Reading

### ISSUE THREAD

**Issue by seiyria** [seiyria/landoftherair#21]
It should be possible to read scrolls and write on scrolls that are empty. Writing on a scroll would be permanent. Players could use scrolls to share information, or just have fun. Possibly, when mailing items (#20), the message would be written on a scroll.

**Comment by cjepson1978** [comment]
In association to Issue #20 , scrolls could be made mandatory for use between mailing, where message bodies are within the scrolls themselves.

Additionally, scrolls could also be used for scribing (eliminating costs to mentalists who imbue items by substitution). But scrolls would contain only one time casts. To get around the limit of casts, scrolls could be crafted into books.  Thus, the benefit of circumventing use of imbue would be equalized by the time consumption used to craft a book.

Further, the separation of imbue and scribing would allow for further enhancements in the imbue skill, such as an onHit() trigger when an imbued item (e.g., sword or armor) is used in combat.

**Comment by seiyria** [comment]
Yes. I do plan to have "spellforging" as a trade skill (these are all still on my whiteboard) and this would be a perfect way to skill it.
